config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'jobs#index'

  resources :jobs, only: [:index, :show] do
    resources :job_applications, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  require 'pg_search'
  include PgSearch::Model
  multisearchable against: [:title]

  has_many :job_language, dependent: :destroy
  has_many :languages, through: :job_language
  has_many :shift_dates, dependent: :destroy
  has_many :job_applications, dependent: :destroy
  validates :title, presence: true, uniqueness: true
  validates :salary, presence: true

  accepts_nested_attributes_for :shift_dates, allow_destroy: true

  def validates_shift_dates
    errors.add(:shift_date, "maximum 7 shift dates allowed") if shift_dates.size > 7
    errors.add(:shift_date, "requires at least 1 shift_date") if shift_dates.empty?
  end

  def total_salary
    salary * total_job_hours
  end

  def total_job_hours
    hours = 0
    shift_dates.each do |sd|
      hours += sd.total_hours
    end
    hours
  end
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :job
  belongs_to :user

  validates_uniqueness_of :job_id, scope: :user_id
end

app/models/job_language.rb
class JobLanguage < ApplicationRecord
  belongs_to :job
  belongs_to :language
end

app/models/language.rb
class Language < ApplicationRecord
  require 'pg_search'
  include PgSearch::Model
  multisearchable against: %i[name_eng name_deu]

  has_many :job_language
  has_many :jobs, through: :job_language
  validates :name_eng, :name_deu, presence: true, uniqueness: true
end

app/models/shift_date.rb
class ShiftDate < ApplicationRecord
  belongs_to :job, inverse_of: :shift_dates
  validates :start_date, :end_date, :hours_per_day, presence: true

  def total_hours
    days = end_date - start_date
    (days * hours_per_day).to_i
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  def create
    user = current_user
    job = Job.find(params[:job_id])
    job_application = JobApplication.new(user: user, job: job)
    if job_application.save
      redirect_to root_path, notice: "Congratulation! You've Successfully Applied For This Job"
    else
      redirect_to root_path, alert: "You've already applied for this job."
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      results = PgSearch.multisearch(params[:query])
      parse_results(results)
    else
      @jobs = Job.all
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  private

  def parse_results(results)
    @jobs = []
    results.each do |result|
      if result.searchable_type == "Job"
        @jobs << result.searchable
      else
        result.searchable.jobs.each do |job|
          @jobs << job
        end
      end
    end
    @jobs
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/index.html.erb
<div>
  <%= form_tag jobs_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search by Job Title or Spoken Language"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  <p>
  <ul>
    <% @jobs.each do |job| %>
      <li>
        <h2>Job Title: <%= link_to  job.title, job_path(job) %> </h2>
        <p> Total Salary: <%= job.total_salary %> <p>
        <p> Languages:
        <% job.languages.each do |language| %>
            <p><%= language.name_eng %></p>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<p> Hourly Rate: <%= @job.salary %>.00 </p>
<p> Total Salary for this job: <%= @job.total_salary %>
<p> Dates Required: </p>
<% @job.shift_dates.each do |sd| %>
  <p><%= sd.start_date.strftime("%d/%b/%Y") %> - <%= sd.end_date.strftime("%d/%b/%Y") %></p>
<% end %>
<%= link_to  "Apply For This Job", job_job_applications_path(job_id: @job.id), method: :post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobSearchSolution</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
    <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Jobs", jobs_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to  "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>

    </ul>
  </div>
</div>